[project]
name = "arc-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arckit>=0.1.0",
    "matplotlib>=3.10.0",
    "streamlit>=1.41.1",
]
